version = 5.7.0
archive_dir = /etc/letsencrypt/archive/auth.forumfordemocracy.net
cert = /etc/letsencrypt/live/auth.forumfordemocracy.net/cert.pem
privkey = /etc/letsencrypt/live/auth.forumfordemocracy.net/privkey.pem
chain = /etc/letsencrypt/live/auth.forumfordemocracy.net/chain.pem
fullchain = /etc/letsencrypt/live/auth.forumfordemocracy.net/fullchain.pem
[renewalparams]
account = 413c900f5eac53d523ea096ebf7d9701
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
auth.forumfordemocracy.net = /var/www/certbot
