version = 5.7.0
archive_dir = /etc/letsencrypt/archive/devspace-oauth
cert = /etc/letsencrypt/live/devspace-oauth/cert.pem
privkey = /etc/letsencrypt/live/devspace-oauth/privkey.pem
chain = /etc/letsencrypt/live/devspace-oauth/chain.pem
fullchain = /etc/letsencrypt/live/devspace-oauth/fullchain.pem
[renewalparams]
account = 413c900f5eac53d523ea096ebf7d9701
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
[acme_renewal_info]
ari_retry_after = 2026-08-20T05:14:55
